### ISSUE TITLE
Ctd after training with dummy and waiting 1 hour 

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#121]
Modlist Version: latest 
Modlist Profile: refined

**Describe the Bug**
Managed to get a ctd in companions training yard. Was training with dummy, bashing (spam) and hitting with my sword. All the companions were standing behind me. After some time training with the dummy. Waited an hour because it looked like they were just stuck. And then they starting moving. After like a min got ctd. No crash log.  

As a note, I had reloaded this save when posted the brawl bug. So I was playing a reloaded save. Obviously might contribute to crash but with the new fix not sure if it's still that. 

**To Reproduce**
Can't seem to reproduce the issue. 

**Expected Behavior**
Not to ctd

**Comment by zediious** [comment]
If you experience something like this habitually, download and install this mod to Mod Organizer https://drive.google.com/file/d/1HmLOtIXBEfeZ-m1-7wgbSJvXZafIcm8C/view?usp=drive_link

Then, whenever you seem to be in a freezing/crash situation, spam the "CTRL+L" key combination about 3-6 times. This should generate a TON of log files in your Overwrite/NetScriptFramework.

Pack those into a zip, and upload those. These can help find why a freeze may be occurring, otherwise, there may have been a memory issue.

I'll close this out. please make a new issue if you find something like this occurring again.
