### ISSUE TITLE
black screen not not loading into iron maidens in whiterun

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#128]
Modlist Version: refined
Modlist Profile: latest

**Describe the Bug**
played the list for like an hour everything fine then went into iron maidens then just didnt load in waited like 15min then had to end take through task manager. it said not responding in task manager dk if that helps.

**Comment by zediious** [comment]
If you experience something like this habitually, download and install this mod to Mod Organizer https://drive.google.com/file/d/1HmLOtIXBEfeZ-m1-7wgbSJvXZafIcm8C/view?usp=drive_link

Then, whenever you seem to be in a infinite loading situation, spam the "CTRL+L" key combination about 3-6 times. This should generate a TON of log files in your Overwrite/NetScriptFramework.

Pack those into a zip, and upload those. These can help find why a freeze may be occurring, otherwise, there may have been a memory issue.

I'll close this out. please make a new issue if you find something like this occurring again.
