### ISSUE TITLE
furious ragdoll upon death

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#25]
This isnt a bug really probably how you intended the game to play when the character dies. I think that when the player does die this style ragdoll flying across seems unrealistic?

**Comment by zediious** [comment]
I don't typically have this experience when I die. Of course there's occasionally something weird that happens, but it's definitely not a habitual thing. Does this happen to you every time you die?

Is it possible for you to get video of this occurring?

Also, have you added anything to the list?

**Comment by AggravatedSpoon** [comment]
I haven't added anything in the mod list. It only happens only when I enter interiors. For example when I went in the mine near Riverwood. Every time I died my player would go on the floor for a split second that all my weapons make a loud dropping sound and my player gets thrown across aggressively.

**Comment by zediious** [comment]
> I haven't added anything in the mod list. It only happens only when I enter interiors. For example when I went in the mine near Riverwood. Every time I died my player would go on the floor for a split second that all my weapons make a loud dropping sound and my player gets thrown across aggressively.

I will do some testing to see if I can find the cause of this, it's likely something to do with Shadow of Skyrim not liking something occurring on death. It may be a known thing I've missed.

**Comment by zediious** [comment]
I have confirmed this is entirely due to the MCM settings for Shadow of Skyrim. I forgot to include the bleedout style and compatibility mode MCM instructions that are required on the Post-Mod List Install wiki page. Now the Shadow of Skyrim MCM section has been changed to require setting this for proper list functionality. I also updated the Overwrite Misc mod to remove the Shadow of Skyrim automation from MCM Recorder since it did not work most of the time anyways.

### Shadow of Skyrim

1) Go to the *Shadow of Skyrim* MCM menu, open the General tab.
2) Open a different tab in the Shadow of Skyrim MCM menu.
3) Open the general tab again.

Check the "Enabled" checkbox and allow the mod to initialize. Make sure you see "Shadow of Skyrim Initialized" at the top left of your screen after it takes you out of the MCM menu. Then, you need to open the MCM menu again and select the following options to set the settings.

1) Respawn Tab > Respawn Location > Set to **Last Location**
2) Defeat Tab > Bleedout Style > Set to Animation (this is a vital setting)
2) Developer Tab > Check Enable Developer Mode AND Compatibility Mode AND Alternate Start Compatibility (these are vital settings)
