### ISSUE TITLE
Attempting to Shoot Arrows at Whiterun Guards does no damage

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#38]
When I shoot at a Whiterun Guard (any for this matter) with a bow, they don't receive damage, and don't become hostile.  I attempted to melee sneak attack to see if it would trigger guards to become hostile and it worked.  Not sure if this is an isolated issue with the bow or if it's an issue attacking non-hostile NPCs. Will continue to test and see if it's just Whiterun Guards affected. Only tested on guards outside of Whiterun, will update if anything changes.

**Comment by zediious** [comment]
This is due to Simple Offence Supression. Open the MCM menu there, and you can allow damage to friendlies. This mod is in the list because Elder Souls - Sweep Attacks made it it way too easy to accidently kill friendlies in combat. I removed that mod when Precision was released. 

In practice though, Precision can also cause the mod to not work properly, and can still cause aggro and hit when you use melee.

It's also possible there's more to it than that, but change the MCM and let me know. I'll see if there's a patch available, I really have not looked since I added Precision.

**Comment by m-ft** [comment]
![489830_20230412233925_1](https://user-images.githubusercontent.com/130550195/231675135-4ac565ee-b32f-4f2d-9de9-61eb0ef9fe6c.png)
It was already checked when I looked at the MCM, toggling it both on and off did not work.  Is there anything else I should try?

**Comment by zediious** [comment]
If that's the case, then there's definitely something else going on. I'll take a look at it, thank you!

**Comment by zediious** [comment]
I have narrowed the problem down the No Follower Attack Collision.

The mod has a configuration option in it's ini file, `bProtectNeutralActor`. This was already set to false, but the mod seemed to be protecting guards no matter what, until you attacked another NPC.

Removing this mod solves the issue. The mod really was not working with MCO anyways, friendlies were still being hit most of the time. Not a big loss. Simple Offence Suppression will remain in and on by default, but you can always disable the option in MCM to prevent accidental hits.
