### ISSUE TITLE
Item Descriptions HUD stops showing after a period of time

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#47]
After a certain period of time, item descriptions will stop popping up.
![232350278-6384f763-e449-40a0-ba22-dbf0e070e222](https://user-images.githubusercontent.com/130550195/232396966-8128ad0f-c3ba-4919-9191-bd039c4caa1e.png)
^^Before^^
![489830_20230416225958_1](https://user-images.githubusercontent.com/130550195/232397134-de91502e-ba62-4922-9764-4e68166da915.png)
^^After^^

**Comment by zediious** [comment]
This has been fixed in dev, by checking the following fields in the default preset for moreHUD MCM. What was happening, is that after changing this MCM setting automatically, the setting wouldn't actually apply until a save reload or a door is entered. I quite like effect descriptions, so this will be enabled permanently.

Target Data tab
- "Show Ingredient Effects"
- "Show Other EffectS"
