### ISSUE TITLE
Big Suggestions Post - Cake is a Lie

### ISSUE THREAD

**Issue by TheCakeisAlie0** [zediious/tpfz-sprinkles#54]
Hi, this is Zediious. I've modified this message to show what I have added, plan to add, or will not add. If there's no added bold text next to a mod, then I decided against it.

## Cosmetic Suggestions 
**Idle Wheel Menu** **ADDED**
(https://www.nexusmods.com/skyrimspecialedition/mods/31516)
**Simple Straw Hats** **ADDED**
(https://www.nexusmods.com/skyrimspecialedition/mods/89962)
**Ave's Silver Sapphire Ring Replacer for Beyond Skyrim - Bruma** **ADDED**
(https://www.nexusmods.com/skyrimspecialedition/mods/89655)
**Ave's Jade Sapphire Ring Replacer for Beyond Skyrim - Bruma** **ADDED**
(https://www.nexusmods.com/skyrimspecialedition/mods/89214)
**Ave's Jade Ring Replacer for Beyond Skyrim - Bruma** **ADDED**
(https://www.nexusmods.com/skyrimspecialedition/mods/88677)
## Animations Suggestions
Guts Animation (includes a new skill for some fun gameplay) **IN FUTURE**
(https://www.nexusmods.com/skyrimspecialedition/mods/87230)
DS3 Ringed Knight Sword **IN FUTURE**
(https://www.nexusmods.com/skyrimspecialedition/mods/86778)
DS3 Lothric Knight Sword
(https://www.nexusmods.com/skyrimspecialedition/mods/87435)
Kingsglaive Moveset **IN FUTURE**
(https://www.nexusmods.com/skyrimspecialedition/mods/81449)
## Audio Suggestions
Eviscerate **ADDED**
(https://www.nexusmods.com/skyrimspecialedition/mods/68884)
Necrome
(https://www.nexusmods.com/skyrimspecialedition/mods/48836)
The Last Vigil **ADDED**
(https://www.nexusmods.com/skyrimspecialedition/mods/41494)
Equus **ADDED**
(https://www.nexusmods.com/skyrimspecialedition/mods/69069)
## Misc
Skyrim's Unique Treasures **MAYBE IN FUTURE**
(https://www.nexusmods.com/skyrimspecialedition/mods/5261)
Dovahkiin's Vault **IN FUTURE**
(https://www.nexusmods.com/skyrimspecialedition/mods/42237)
Gemstone Collector Remaster **MAYBE IN FUTURE**
(https://www.nexusmods.com/skyrimspecialedition/mods/3393)
Mudcrab Merchant **MAYBE IN FUTURE**
(https://www.nexusmods.com/skyrimspecialedition/mods/27272)

# More Suggestions

# New Items
## Armor
[Winged Hussar Armor & Weapons](https://www.nexusmods.com/skyrimspecialedition/mods/89496)
[Barsaebic Ayleid Armor](https://www.nexusmods.com/skyrimspecialedition/mods/85917)
[Rormasu Armor](https://www.nexusmods.com/skyrimspecialedition/mods/73757)
[Argonia Apparel Integration SPID](https://www.nexusmods.com/skyrimspecialedition/mods/88468) _<sub>This mod distributes both the Barsaebic & Rormasu armor into the world</sub>_
[Nordic Steel Helmet](https://www.nexusmods.com/skyrimspecialedition/mods/88288)

## Weapons
[Valermos](https://www.nexusmods.com/skyrimspecialedition/mods/89361) **NEW SUGGESTION**
[Valermos - Dagger](https://www.nexusmods.com/skyrimspecialedition/mods/89617) _<sub>Require base Valermos mod</sub>_ **NEW SUGGESTION**
[Violet Bloody Blades](https://www.nexusmods.com/skyrimspecialedition/mods/88656) **NEW SUGGESTION**
[Blades of Chaos](https://www.nexusmods.com/skyrimspecialedition/mods/89815) **NEW SUGGESTION**
[Zaklinak's Weapon Pack](https://www.nexusmods.com/skyrimspecialedition/mods/89573 )**NEW SUGGESTION**
[Phoenix Staff](https://www.nexusmods.com/skyrimspecialedition/mods/89863) **NEW SUGGESTION**
[Dwemer Tonal Weaponry](https://www.nexusmods.com/skyrimspecialedition/mods/89588) **NEW SUGGESTION**
[Knightblade](https://www.nexusmods.com/skyrimspecialedition/mods/89630) **NEW SUGGESTION**
[Meme Weapon :)](https://www.nexusmods.com/skyrimspecialedition/mods/89419) **NEW SUGGESTION**
[Regal Rapier & Dainty Dirk](https://www.nexusmods.com/skyrimspecialedition/mods/35729) **NEW SUGGESTION**
[Sting Spear](https://www.nexusmods.com/skyrimspecialedition/mods/64123) **NEW SUGGESTION**
[Yol'Kreh ](https://www.nexusmods.com/skyrimspecialedition/mods/59970) **NEW SUGGESTION**

**Comment by zediious** [comment]
All the Cosmetic suggestions will make their way in for the next version :)

### Animations - These will come later
The Guts animation is super cool. I will take some time to see if I can apply it to the list well. I have yet to add any extra special movesets like that, because I want to take the time and make sure it can be gotten in a fair way and that it's balanced in some way. Likely requirements for the moveset to trigger will be a high level in two handed, probably a perk from that tree, and only with very large greatswords like this. Possibly something else. The speed will also be reduced a tad bit for sure. The same goes for the Ringed Knight moveset.

The Lothric Knight moveset only contains 4 light attacks (no power attacks), so it would be inconsistent with the rest of the animations in the list. Only reason I'm avoiding that.

Kingsglaive is something I tested quite some time ago, and had some issues with it. It's likely I can get it working with the list, and would like to. Definitely something I will want to lock behind decent combat skills and conjuration. The movesets are pretty wild and could be quite OP. They'll be looked at!

### Sounds - Mixed

Eviscerate looks nice! I don't like the sword drawing animations much (too stylized for my taste), but the impact sounds are fantastic. When this is implemented, it will be done without sword drawing sounds, instead continuing to use the ISC sounds.

I've seen Necrome before and the sounds are super great, but my one gripe is that the Skeletons breathe. I've always been put off by that, and we use Skeletons Don't Breathe in this mod list to replace that sound with just bones creaking. I *might* add this in and only use the attacking sounds they've replaced.

The Ebony Warrior revoice is great! Adding the Helmet version into the next version.

Equus sounds really great! I am *slightly* iffy on it because I feel Skyrim's horses would have a lot more **umph** to their steps than the mod provides. I have added the mod in, but we're still using the footstep sounds from Improved Horse Step Sounds. All the other sounds Equus provides are fantastic and are in the list now.

### Misc

Skyrim Unique Treasures looks neat, I do like the idea. Adding it however will be a process, so if it does come it will be later on. Same goes for Gemstone Collector

Dovahkiin's Vault is great! I am planning an update in the future where I will be adding a not insignificant amount of player homes to the list. This will more than likely be among them :)

The Mudcrab Merchant is hilarious, and I suppose not *too* outside the scope of Elder Scrolls lore, but it might be a bit too goofy for me. We'll see.

**Comment by TheCakeisAlie0** [comment]
I'll most likely keep updating this every couple of days!

**Comment by zediious** [comment]
Your new suggestions all look awesome, and I'll see to integrating certain ones in the next version :)

**Comment by zediious** [comment]
[Winged Hussar Armor & Weapons](https://www.nexusmods.com/skyrimspecialedition/mods/89496):
- Was in my bookmarks, will be in the next version :)

[Barsaebic Ayleid Armor](https://www.nexusmods.com/skyrimspecialedition/mods/85917), [Rormasu Armor](https://www.nexusmods.com/skyrimspecialedition/mods/73757) and [Argonia Apparel Integration SPID](https://www.nexusmods.com/skyrimspecialedition/mods/88468)
- These look great! I would normally manually choose where to put armors, but the SPID addon there does it in a way I am happy with. All three of these are in the list for the next version.

[Nordic Steel Helmet](https://www.nexusmods.com/skyrimspecialedition/mods/88288)
- This looks nice! It will be added and included in Steel Helmet lists.

[Valermos](https://www.nexusmods.com/skyrimspecialedition/mods/89361)
- Gnarly looking sword! It will be included as Daedric weapon, along with the Dagger version.

[Violet Bloody Blades](https://www.nexusmods.com/skyrimspecialedition/mods/88656)
- This was suggested in another issue, I plan to integrate some twinblade mods in the future, this will be among them.

[Blades of Chaos](https://www.nexusmods.com/skyrimspecialedition/mods/89815):
- I will add these in, and keep their Daedric crafting requisite while also adding them to leveled lists.

[Zaklinak's Weapon Pack](https://www.nexusmods.com/skyrimspecialedition/mods/89573):
- Two of these look neat to me, but I think I'm going to pass on this one.

[Phoenix Staff](https://www.nexusmods.com/skyrimspecialedition/mods/89863)
- These look neat, but the Staves in the game already look quite nice, and it's just Wall of Flames as far as I can see.

[Dwemer Tonal Weaponry](https://www.nexusmods.com/skyrimspecialedition/mods/89588)
- This is super cool, and I think it's default crafting upgrade requirements of Enchanting and Destruction will work out famously! I will include this, and make any balance modifications needed as I do a test playthrough.

[Knightblade](https://www.nexusmods.com/skyrimspecialedition/mods/89630)
- This looks cool, but I think I'm going to pass on this one.

[Meme Weapon :)](https://www.nexusmods.com/skyrimspecialedition/mods/89419)
- Need I say more :)

[Regal Rapier & Dainty Dirk](https://www.nexusmods.com/skyrimspecialedition/mods/35729)
- These look very nice! They will be included in Steel lists

[Sting Spear](https://www.nexusmods.com/skyrimspecialedition/mods/64123):
- This looks awesome! It will be included as a "halberd" in the Nordic leveled lists, changing COBJ and damage to match.

[Yol'Kreh](https://www.nexusmods.com/skyrimspecialedition/mods/59970)
- Love more scythes! The default crafting mechanic for the fiery variant looks neat, I'll keep/patch that and the Ebony tier for the base scythe.

<hr>

Thanks for all your suggestions! I will close this out when a version with the chosen mods has been released.
