### ISSUE TITLE
Some mods suggestion

### ISSUE THREAD

**Issue by RealOctoDude** [zediious/tpfz-sprinkles#59]
QOL
https://www.nexusmods.com/skyrimspecialedition/mods/89163?tab=files
Save a lot of times
https://www.nexusmods.com/skyrimspecialedition/mods/64764
No stamina cost sprint outside of combat

Armor/weapons
https://www.nexusmods.com/skyrimspecialedition/mods/87272
https://www.nexusmods.com/skyrimspecialedition/mods/37610
https://www.nexusmods.com/skyrimspecialedition/mods/6227
https://www.nexusmods.com/skyrimspecialedition/mods/88656

**Comment by zediious** [comment]
I will make sure Instantly Skip Dialogue works well with some of the modded quests we're using. By that mod's nature, I can expect quite a few quests to bug out expecting the player to not be able to skip certain dialogue.

We are already using [this mod](https://www.nexusmods.com/skyrimspecialedition/mods/78618) to do what Elden Sprint does, and with an SKSE implementation instead of Skyrim Platform.

I will check out all of those equipment mods! Always looking for more :)
