### ISSUE TITLE
Some bugs, improvements, and mod suggestions

### ISSUE THREAD

**Issue by FenguFengu** [zediious/tpfz-sprinkles#63]
* means I added text here - Zediious

Bugs:
- Vanilla start has horses bugged, they get crazy with physics, or got stuck walking into walls. Needed to 'tcl' horse and cart to finish intro. 
- Also Alduin not disappearing and blocking the way. *(FIXED FOR NEXT VERSION)
- When casting bound sword (or any?), while having weapon in right hand, make character take weird stance that correct itself on strong attack
- When using magic with weapon there are 2 crosshairs on the screen *(FIXED FOR NEXT VERSION)

Improvements:
- ~~Add~~ *fix* oxygen meter please! :> *(FIXED FOR NEXT VERSION)
- IDK, but having character play animation every single time you picking something can get kind of annoying after a while, can be bypassed by going 1st person but its it really good idea yo having something like that? I mean quite long animation every time you picking something?

Mod suggestion:
https://www.nexusmods.com/skyrim/mods/2973?tab=description
make FUS RO DAH super epic like in trailers

**Comment by zediious** [comment]
1) Have not experienced this at any point with the list! This is caused in 99% of cases due to script load at the beginning of the game. It is alleviated by alternate start mods (like Alternate Perspective) by allowing mods to load everything they need before initiating the actual cart intro sequence. If you're experiencing that, something abnormal is occurring. 
  - Are you allowing the MCM and all notification messages at the top left of the screen to finish before continuing?
  - Have you modified the list (especially anything regarding the game start) in any way?

2) I will run through the intro a few times to test Alduin disappearing, but I have also not experienced this since the latest version.

3) Will check this out!

4) Will check this out!

5) The list already does use Oxygen Meter, are you finding that it is not working?

6) All personal preference here. I prefer to see my character interact with the world at every opportunity. Immersive Interactions has an MCM menu where you are able to turn off every feature of the mod if you wish.

7) I'll check this out in game. I do like consistency, so if it deviates *too* much from the rest of the shouts, it would throw me off. Will be looked at.

**Comment by FenguFengu** [comment]
1. About horse 
- I had save after every mcm and nemesis were loaded, and started from there choosing different starting options. 
- I did not modify list in anyway expect changing controls in game options (sprint, sneak etc.)

5. About oxygen meter:
- Maybe I'm blind but I could not see it anywhere, I will post screenshot on discord when in the water maybe its just well hidden xD

6. That's awesome, I thought its permanent.

**Comment by zediious** [comment]
I've opted against the "Real Fus-Ro-Dah" mod. It's quite cool, I just dislike how much it deviates from the rest of the shouts. If they all could be done in a similar fashion, it would be neat.
