### ISSUE TITLE
Suggestion for Sunhelm

### ISSUE THREAD

**Issue by TheLGD27** [zediious/tpfz-sprinkles#67]
I know that this was in a closed thread but personally as someone who always likes survival mods sunhelm is miles ahead of survival mode. It's really simple and i think it would fit in really nicely for those that want a survival mode. CC survival mod just kind of sucks

**Comment by zediious** [comment]
As I mentioned in Discord, I'll more than likely cave and add this as an optional mod, since I've already implemented Campfire as an optional mod for the next version.

Re-iterating again, Survival is not a focus of this mod list at all, and these will be offered as optional mods, such that users can use them and still maintain official support for the list.
