### ISSUE TITLE
Suggestion: Ev1l's Suggestions

### ISSUE THREAD

**Issue by Ev1lVaultBoy** [zediious/tpfz-sprinkles#76]
More Growable Plants:

https://www.nexusmods.com/skyrimspecialedition/mods/58880
There's plenty of additions for expansion mods too on Webmetz's profile
https://www.nexusmods.com/users/78185753?tab=user+files&BH=3

Don't Eat Spelltomes (I saw someone else's spell learning suggestion)
https://www.nexusmods.com/skyrimspecialedition/mods/43095

Dynamic Pickpocket Cap:
https://www.nexusmods.com/skyrimspecialedition/mods/17273

XP For Failed Pickpocket:
https://www.nexusmods.com/skyrimspecialedition/mods/59909

Freshly Picked (Picking plants gives XP): 
https://www.nexusmods.com/skyrimspecialedition/mods/17259

Recoil on objects:
https://www.nexusmods.com/skyrimspecialedition/mods/70719

Increase Speech By Reading:
https://www.nexusmods.com/skyrimspecialedition/mods/16338

Legendary Skill Bonus:
https://www.nexusmods.com/skyrimspecialedition/mods/77274

More (preference for my personal balance) mods if they sound interesting

Genders Are Boringly Indistinct:
https://www.nexusmods.com/skyrimspecialedition/mods/23145
Race And Gender Diversification:
https://www.nexusmods.com/skyrimspecialedition/mods/73858
Classes:
https://www.nexusmods.com/skyrimspecialedition/mods/41298
-Reminiscent of old game mechanics

Conditional Stamina (Only for the sneaking stamina really):
https://www.nexusmods.com/skyrimspecialedition/mods/72882
Simple Degradation (I don't remember if there's a degradation mod but it probably doesn't fit in the modlist anyway):
https://www.nexusmods.com/skyrimspecialedition/mods/74790
Spelltome Studies (Minigames for spell learning):
https://www.nexusmods.com/skyrimspecialedition/mods/71565

Stuff that people probably wouldn't like that I would personally add:
Save By Journaling And Sleeping:
https://www.nexusmods.com/skyrimspecialedition/mods/73258
Equipment Restriction By Skill:
https://www.nexusmods.com/skyrimspecialedition/mods/22830
Trainers Galore (Anyone can train pretty much):
https://www.nexusmods.com/skyrimspecialedition/mods/20360

Some of these suggestions might be redundant because I copy and paste this for different lists, but most of them aren't in it

**Comment by zediious** [comment]
Thanks for the suggestions! I will comb through here when it comes time for me to get to my bookmarks/suggestions and I will update regarding each one :)

**Comment by Ev1lVaultBoy** [comment]
Awesome, thank you!

**Comment by zediious** [comment]
More Growable Plants:
- Since we're not using the full AE, I've opted for [this one](https://www.nexusmods.com/skyrimspecialedition/mods/30729?tab=description) instead. Thanks for the heads up there!

Don't Eat Spell Tomes:
- As you mentioned, another suggestion for that is included in the next version, specifically [this mod](https://www.nexusmods.com/skyrimspecialedition/mods/45514)

Dynamic Pickpocket Cap:
- This is neat, but Adamant/Hand to Hand's Security perk tree includes a perk to raise your cap to 100% later in the tree, I feel this would not align with that very well.

XP For Failed Pickpocket:
- This looks great! I'll ensure there is no feature overlap and include in the next version.

Freshly Picked (Picking plants gives XP):
- This looks interesting, but appears to also give Alchemy XP when picking up Gold as well. I'll see if I can disable that functionality, but this will likely not be included.

Recoil on objects:
- This functionality is already included with Precision

Increase Speech By Reading:
- Had this one in my bookmarks, it will be included in the next version.

Legendary Skill Bonus:
- This is nice! I never reset my skills anyways, so this works great. It will be in the next version.

Genders Are Boringly Indistinct, Race And Gender Diversification, Classes:
- The gender diversification mods are cool, but I generally prefer to just have the same bonuses for male/female. It does make for more variety, but that's just not for me personally.
- In terms of classes, we already have Dealing with Backstories and Sets of Skills for a somewhat lite implementation of that. I would prefer to stick to just that.

Conditional Stamina (Only for the sneaking stamina really):
- This is a great concept, but I'm not sure how much I would enjoy sneaking at all draining stamina. It seems that it would be impossible to configure only moving while sneaking to consume stamina, which would be my ideal configuration.

Simple Degradation (I don't remember if there's a degradation mod but it probably doesn't fit in the modlist anyway):
- Parroting you, I've never been a fan of Degradation mods in Skyrim. It does fit a certain type of list.

Spelltome Studies (Minigames for spell learning):
- The above mentioned Spell Tome mod adds similar functionality to learning a spell book.

Save By Journaling And Sleeping:
- For me, No Saving in Combat is about the limit with save restrictions. I am too paranoid with a random crash (happens to me often enough, GPU is on it's last legs) to limit my saving in such a way. The idea, however, is very nice.

Equipment Restriction By Skill:
- This is a great idea in theory. Pulls it's notions from my second favorite game series ever ;) I *think* this would mesh into the list quite well given how much variety there is within each tier. I'm not sure if I want to include it in the list however. I'll keep it on my backburner and test around with it. Thank you for the suggestion!

Trainers Galore (Anyone can train pretty much):
- While cool, I would prefer to keep trainers how they are.

<hr>

Thank you for all your suggestions! I will close this out when a version containing chosen suggestions is released.
