### ISSUE TITLE
Enemy spell causing crashes.

### ISSUE THREAD

**Issue by Ohrumon** [zediious/tpfz-sprinkles#92]
I'm not sure exactly what spell it is, but it sounds like a lightning one that has been causing me consistent crashes in my playthrough. I didn't see this issue reported anywhere else. Its happened to me on two separate occasions, and I narrowed it down to crashing when the bandit began casting their spell. One of the locations (not sure if this will be helpful or not) is Orphans Tear, north of Solitude, and the other is Traitor's Post, east of Windhelm. The only way Ive found to get through both of these instances is to rush the mage with that specific spell.

Note: Im truly unsure which spell it is as I only hear the sound effect before the game crashes and see their palm start glowing blue. I've seen plenty of all elemental spells go off in battles and only run into this exact issue twice.

**Comment by zediious** [comment]
Hello! Shortly before this issue was opened, an update to the list was released updating a variety of spell mods, which fixed a certain crash with a shadow spell. This may have also been related. I will close this relating to that, do re-open if you experience this again on the latest version :)

https://zediious.github.io/tpfz-sprinkles/docs/other-info/changelog/#v0955---12312023
